// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdUt8O4xR8ghxap-glyslef6SfTJzXFo4',
    appId: '1:617783758084:web:f3bda0a1b043667d2a5451',
    messagingSenderId: '617783758084',
    projectId: 'slide-puzzle-d6a68',
    authDomain: 'slide-puzzle-d6a68.firebaseapp.com',
    storageBucket: 'slide-puzzle-d6a68.appspot.com',
    measurementId: 'G-42NRTZK0BV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSVqu2qzd3GU3fhOWW8oI_XQ-pW_9nLDU',
    appId: '1:617783758084:android:5a6507d624ced2ae2a5451',
    messagingSenderId: '617783758084',
    projectId: 'slide-puzzle-d6a68',
    storageBucket: 'slide-puzzle-d6a68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATBs_9er_fEXlKhBWslGHcAhmP9WWXqH8',
    appId: '1:617783758084:ios:75a35e565297ad122a5451',
    messagingSenderId: '617783758084',
    projectId: 'slide-puzzle-d6a68',
    storageBucket: 'slide-puzzle-d6a68.appspot.com',
    iosClientId: '617783758084-qg3qdc3uktkqht5r4lg1cklad25g8r8t.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.dev',
  );
}
